// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnitzCore.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SnitzDbContext))]
    partial class SnitzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Snitz.Events.Models.CalendarEventItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("C_ID");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AUTHOR_ID");

                    b.Property<int?>("CatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<int?>("ClubId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CLUB_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("EVENT_DETAILS");

                    b.Property<string>("End")
                        .HasColumnType("TEXT")
                        .HasColumnName("EVENT_ENDDATE");

                    b.Property<bool>("IsAllDayEvent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EVENT_ALLDAY");

                    b.Property<int?>("LocId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOC_ID");

                    b.Property<string>("Posted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATE_ADDED");

                    b.Property<string>("RecurDays")
                        .HasColumnType("TEXT")
                        .HasColumnName("EVENT_DAYS");

                    b.Property<int>("Recurs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EVENT_RECURS");

                    b.Property<string>("Start")
                        .HasColumnType("TEXT")
                        .HasColumnName("EVENT_DATE");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("EVENT_TITLE");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CatId");

                    b.HasIndex("ClubId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LocId");

                    b.HasIndex("TopicId");

                    b.ToTable("CAL_EVENTS");
                });

            modelBuilder.Entity("Snitz.Events.Models.ClubCalendarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CAT_NAME");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ORDER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("EVENT_CAT");
                });

            modelBuilder.Entity("Snitz.Events.Models.ClubCalendarClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CLUB_ID");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CLUB_ABBR");

                    b.Property<int>("DefLocId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CLUB_DEF_LOC");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CLUB_L_NAME");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CLUB_ORDER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CLUB_S_NAME");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("EVENT_CLUB");
                });

            modelBuilder.Entity("Snitz.Events.Models.ClubCalendarLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOC_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LOC_NAME");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOC_ORDER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("EVENT_LOCATION");
                });

            modelBuilder.Entity("Snitz.PhotoAlbum.Models.AlbumCategory", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CAT_DESC");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.HasKey("CatId");

                    b.ToTable("FORUM_IMAGE_CAT");
                });

            modelBuilder.Entity("Snitz.PhotoAlbum.Models.AlbumGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("O_GROUP_ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("O_GROUP_NAME");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("O_GROUP_ORDER");

                    b.HasKey("Id");

                    b.ToTable("FORUM_ORG_GROUP");
                });

            modelBuilder.Entity("Snitz.PhotoAlbum.Models.AlbumImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_ID");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_CAT");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_NORWEGIANNAME");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_DESC");

                    b.Property<bool>("DoNotFeature")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_NOTFEATURED");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_GROUP_ID");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_HEIGHT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_PRIVATE");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_LOC");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_MID");

                    b.Property<string>("Mime")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_TYPE");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_SCIENTIFICNAME");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_SIZE");

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("I_DATE");

                    b.Property<int?>("Views")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_VIEWS");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("I_WIDTH");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_IMAGES");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ArchivedPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.Property<int>("AllowRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ALLOW_RATING");

                    b.Property<int?>("ArchiveFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ARCHIVE_FLAG");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_DATE");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_IP");

                    b.Property<short>("IsSticky")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_STICKY");

                    b.Property<short>("Ispoll")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ISPOLL");

                    b.Property<string>("LastEdit")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_LAST_EDIT");

                    b.Property<int?>("LastEditby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_EDITBY");

                    b.Property<int?>("LastPostAuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_POST_AUTHOR");

                    b.Property<string>("LastPostDate")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_LAST_POST");

                    b.Property<int?>("LastPostReplyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_POST_REPLY_ID");

                    b.Property<short>("Mail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_MAIL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_AUTHOR");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("T_MESSAGE");

                    b.Property<short>("Pollstatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_POLLSTATUS");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_RATING_TOTAL");

                    b.Property<int>("RatingTotalCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_RATING_TOTAL_COUNT");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_REPLIES");

                    b.Property<short>("Sig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_SIG");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_STATUS");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_SUBJECT");

                    b.Property<int>("UnmoderatedReplies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_UREPLIES");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_VIEW_COUNT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ForumId");

                    b.HasIndex("LastPostAuthorId");

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_A_TOPICS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ArchivedReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("REPLY_ID");

                    b.Property<int>("ArchivedPostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("R_MESSAGE");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_DATE");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_IP");

                    b.Property<int?>("LastEditby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_LAST_EDITBY");

                    b.Property<string>("LastEdited")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_LAST_EDIT");

                    b.Property<short>("Mail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_MAIL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_AUTHOR");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_RATING");

                    b.Property<short>("Sig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_SIG");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedPostId");

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_A_REPLY");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Badword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("B_ID");

                    b.Property<string>("ReplaceWith")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("B_REPLACE");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("B_BADWORD");

                    b.HasKey("Id");

                    b.ToTable("FORUM_BADWORDS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.BookmarkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("BOOKMARK_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("B_MEMBERID");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("B_TOPICID");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TopicId");

                    b.ToTable("FORUM_BOOKMARKS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<int?>("Moderation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_MODERATION");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("CAT_NAME");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ORDER");

                    b.Property<short?>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_STATUS");

                    b.Property<int?>("Subscription")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_SUBSCRIPTION");

                    b.HasKey("Id");

                    b.ToTable("FORUM_CATEGORY");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<int>("ArchiveSched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_ARCHIVE_SCHED");

                    b.Property<int?>("ArchivedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_A_COUNT");

                    b.Property<int>("ArchivedTopics")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_A_TOPICS");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<short>("CountMemberPosts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_COUNT_M_POSTS");

                    b.Property<int>("Defaultdays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_DEFAULTDAYS");

                    b.Property<int>("DeleteSched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_DELETE_SCHED");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("F_DESCRIPTION");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT")
                        .HasColumnName("F_IP");

                    b.Property<string>("LastArchived")
                        .HasColumnType("TEXT")
                        .HasColumnName("F_L_ARCHIVE");

                    b.Property<string>("LastDelete")
                        .HasColumnType("TEXT")
                        .HasColumnName("F_L_DELETE");

                    b.Property<string>("LastPost")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("F_LAST_POST");

                    b.Property<int?>("LastPostAuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_LAST_POST_AUTHOR");

                    b.Property<int?>("LatestReplyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_LAST_POST_REPLY_ID");

                    b.Property<int?>("LatestTopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_LAST_POST_TOPIC_ID");

                    b.Property<short>("Mail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_MAIL");

                    b.Property<int>("Moderation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_MODERATION");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_ORDER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("F_PASSWORD_NEW");

                    b.Property<int>("Polls")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_POLLS");

                    b.Property<int>("Postauth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_POSTAUTH");

                    b.Property<int>("Privateforums")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_PRIVATEFORUMS");

                    b.Property<short>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_RATING");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_COUNT");

                    b.Property<int>("Replyauth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_REPLYAUTH");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_STATUS");

                    b.Property<int>("Subscription")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_SUBSCRIPTION");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("F_SUBJECT");

                    b.Property<int>("TopicCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_TOPICS");

                    b.Property<short>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("F_TYPE");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("F_URL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LastPostAuthorId");

                    b.HasIndex("LatestTopicId");

                    b.ToTable("FORUM_FORUM");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumAllowedMember", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.HasIndex("ForumId");

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_ALLOWED_MEMBERS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumModerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MOD_ID");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<short?>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MOD_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_MODERATOR");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumTotal", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("COUNT_ID");

                    b.Property<int>("ArchivedPostCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("P_A_COUNT");

                    b.Property<int>("ArchivedTopicCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_A_COUNT");

                    b.Property<int>("PostCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("P_COUNT");

                    b.Property<int>("TopicCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_COUNT");

                    b.Property<int>("UserCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("U_COUNT");

                    b.HasKey("Id");

                    b.ToTable("FORUM_TOTALS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("GROUP_KEY");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GROUP_CATID");

                    b.Property<int?>("GroupNameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GROUP_ID");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupNameId");

                    b.ToTable("FORUM_GROUPS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.GroupName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("GROUP_DESCRIPTION");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("GROUP_ICON");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("GROUP_IMAGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("GROUP_NAME");

                    b.HasKey("Id");

                    b.ToTable("FORUM_GROUP_NAMES");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.LanguageResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ResourceId");

                    b.Property<string>("ResourceSet")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LANGUAGE_RES");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<string>("Age")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_AGE");

                    b.Property<string>("Aim")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_AIM");

                    b.Property<short>("Allowemail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_ALLOWEMAIL");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("M_BIO");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_CITY");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_COUNTRY");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_DATE");

                    b.Property<int>("DefaultView")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_DEFAULT_VIEW");

                    b.Property<string>("Dob")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_EMAIL");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_FIRSTNAME");

                    b.Property<short>("HideEmail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_HIDE_EMAIL");

                    b.Property<string>("Hobbies")
                        .HasColumnType("TEXT")
                        .HasColumnName("M_HOBBIES");

                    b.Property<string>("Homepage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_HOMEPAGE");

                    b.Property<string>("Icq")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_ICQ");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_IP");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_KEY");

                    b.Property<string>("LastIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LAST_IP");

                    b.Property<string>("LastLogin")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LASTHEREDATE");

                    b.Property<string>("Lastactivity")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LASTACTIVITY");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LASTNAME");

                    b.Property<string>("Lastpostdate")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LASTPOSTDATE");

                    b.Property<short>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_LEVEL");

                    b.Property<string>("Link1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LINK1");

                    b.Property<string>("Link2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LINK2");

                    b.Property<string>("Lnews")
                        .HasColumnType("TEXT")
                        .HasColumnName("M_LNEWS");

                    b.Property<string>("Marstatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_MARSTATUS");

                    b.Property<string>("Msn")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_MSN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_NAME");

                    b.Property<string>("Newemail")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_NEWEMAIL");

                    b.Property<string>("Occupation")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_OCCUPATION");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_PHOTO_URL");

                    b.Property<int>("Pmemail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_PMEMAIL");

                    b.Property<int>("Pmreceive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_PMRECEIVE");

                    b.Property<short>("Pmsavesent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_PMSAVESENT");

                    b.Property<int>("Posts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_POSTS");

                    b.Property<short>("Privateprofile")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_PRIVATEPROFILE");

                    b.Property<string>("Pwkey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_PWKEY");

                    b.Property<string>("Quote")
                        .HasColumnType("TEXT")
                        .HasColumnName("M_QUOTE");

                    b.Property<short>("ReceiveEmail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_RECEIVE_EMAIL");

                    b.Property<string>("Sex")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_SEX");

                    b.Property<short?>("Sha256")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_SHA256");

                    b.Property<short>("SigDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_SIG_DEFAULT");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT")
                        .HasColumnName("M_SIG");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_STATE");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_STATUS");

                    b.Property<short>("Subscription")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_SUBSCRIPTION");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_TITLE");

                    b.Property<short>("ViewSig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_VIEW_SIG");

                    b.Property<string>("Yahoo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_YAHOO");

                    b.HasKey("Id");

                    b.ToTable("FORUM_MEMBERS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.MemberNamefilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("N_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("N_NAME");

                    b.HasKey("Id");

                    b.ToTable("FORUM_NAMEFILTER");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.MemberRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RANK_ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_IMAGE");

                    b.Property<int>("ImgRepeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_IMG_REPEAT");

                    b.Property<int?>("Posts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_POSTS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_TITLE");

                    b.HasKey("Id");

                    b.ToTable("FORUM_RANKING");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.MemberSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SUBSCRIPTION_ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ForumId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PostId");

                    b.ToTable("FORUM_SUBSCRIPTIONS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.OldMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("webpages_Membership");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.OldRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("webpages_Roles");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.OldUserInRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("webpages_UsersInRoles");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLL_ID");

                    b.Property<int>("CatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<string>("Lastvote")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("P_LASTVOTE");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("P_QUESTION");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.Property<string>("Whovotes")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("P_WHOVOTES");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("FORUM_POLLS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PollAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLLANSWER_ID");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLLANSWER_COUNT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("POLLANSWER_LABEL");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLLANSWER_ORDER");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLL_ID");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("FORUM_POLL_ANSWERS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLLVOTES_ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<int>("GuestVote")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GUEST_VOTE");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("POLL_ID");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("FORUM_POLL_VOTES");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.Property<int>("AllowRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ALLOW_RATING");

                    b.Property<bool>("Answered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ANSWERED");

                    b.Property<int?>("ArchiveFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ARCHIVE_FLAG");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("T_MESSAGE");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_DATE");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_IP");

                    b.Property<short>("IsSticky")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_STICKY");

                    b.Property<short>("Ispoll")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_ISPOLL");

                    b.Property<string>("LastEdit")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_LAST_EDIT");

                    b.Property<int?>("LastEditby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_EDITBY");

                    b.Property<int?>("LastPostAuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_POST_AUTHOR");

                    b.Property<string>("LastPostDate")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_LAST_POST");

                    b.Property<int?>("LastPostReplyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_LAST_POST_REPLY_ID");

                    b.Property<short>("Mail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_MAIL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_AUTHOR");

                    b.Property<short>("Pollstatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_POLLSTATUS");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_RATING_TOTAL");

                    b.Property<int>("RatingTotalCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_RATING_TOTAL_COUNT");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_REPLIES");

                    b.Property<short>("Sig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_SIG");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("T_SUBJECT");

                    b.Property<int>("UnmoderatedReplies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_UREPLIES");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_VIEW_COUNT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ForumId");

                    b.HasIndex("LastPostAuthorId");

                    b.HasIndex("MemberId");

                    b.ToTable("FORUM_TOPICS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PostReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("REPLY_ID");

                    b.Property<bool>("Answer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_ANSWER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("R_MESSAGE");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_DATE");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FORUM_ID");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_IP");

                    b.Property<int?>("LastEditby")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_LAST_EDITBY");

                    b.Property<string>("LastEdited")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("R_LAST_EDIT");

                    b.Property<short>("Mail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_MAIL");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_AUTHOR");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOPIC_ID");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_RATING");

                    b.Property<short>("Sig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_SIG");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PostId");

                    b.ToTable("FORUM_REPLY");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_ID");

                    b.Property<int>("From")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_FROM");

                    b.Property<int>("HideFrom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PM_DEL_FROM");

                    b.Property<int>("HideTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PM_DEL_TO");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_MAIL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("M_MESSAGE");

                    b.Property<string>("Pmcount")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_PMCOUNT");

                    b.Property<int>("Read")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_READ");

                    b.Property<short>("SaveSentMessage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_OUTBOX");

                    b.Property<string>("SentDate")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_SENT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("M_SUBJECT");

                    b.Property<int>("To")
                        .HasColumnType("INTEGER")
                        .HasColumnName("M_TO");

                    b.HasKey("Id");

                    b.ToTable("FORUM_PM");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PrivateMessageBlocklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("BL_ID");

                    b.Property<int>("BlockedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BL_BLOCKED_ID");

                    b.Property<string>("BlockedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("BL_BLOCKED_NAME");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BL_MEMBER_ID");

                    b.HasKey("Id");

                    b.ToTable("FORUM_PM_BLOCKLIST");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.SnitzConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("C_VARIABLE");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("C_VALUE");

                    b.HasKey("Id");

                    b.ToTable("FORUM_CONFIG_NEW");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.SpamFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("SPAM_ID");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("SPAM_SERVER");

                    b.HasKey("Id");

                    b.ToTable("FORUM_SPAM_MAIL");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.TopicRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RATING");

                    b.Property<int>("RatingsBymemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RATINGS_BYMEMBER_ID");

                    b.Property<int>("RatingsTopicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RATINGS_TOPIC_ID");

                    b.HasKey("Id");

                    b.ToTable("TOPIC_RATINGS");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserDescription")
                        .HasColumnType("TEXT");

                    b.HasIndex("MemberId");

                    b.HasDiscriminator().HasValue("ForumUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Snitz.Events.Models.CalendarEventItem", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Member", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Snitz.Events.Models.ClubCalendarCategory", "Cat")
                        .WithMany()
                        .HasForeignKey("CatId");

                    b.HasOne("Snitz.Events.Models.ClubCalendarClub", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId");

                    b.HasOne("Snitz.Events.Models.ClubCalendarLocation", "Loc")
                        .WithMany()
                        .HasForeignKey("LocId");

                    b.HasOne("SnitzCore.Data.Models.Post", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Cat");

                    b.Navigation("Club");

                    b.Navigation("Loc");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Snitz.PhotoAlbum.Models.AlbumImage", b =>
                {
                    b.HasOne("Snitz.PhotoAlbum.Models.AlbumCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Snitz.PhotoAlbum.Models.AlbumGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ArchivedPost", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Forum", "Forum")
                        .WithMany("ArchivedPosts")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "LastPostAuthor")
                        .WithMany()
                        .HasForeignKey("LastPostAuthorId");

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Forum");

                    b.Navigation("LastPostAuthor");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ArchivedReply", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.ArchivedPost", "Topic")
                        .WithMany("Replies")
                        .HasForeignKey("ArchivedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.BookmarkEntry", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Post", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Forum", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Category", "Category")
                        .WithMany("Forums")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "LastPostAuthor")
                        .WithMany()
                        .HasForeignKey("LastPostAuthorId");

                    b.HasOne("SnitzCore.Data.Models.Post", "LatestTopic")
                        .WithMany()
                        .HasForeignKey("LatestTopicId");

                    b.Navigation("Category");

                    b.Navigation("LastPostAuthor");

                    b.Navigation("LatestTopic");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumAllowedMember", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumModerator", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Forum", null)
                        .WithMany("ForumModerators")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Group", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.GroupName", "GroupName")
                        .WithMany("Groups")
                        .HasForeignKey("GroupNameId");

                    b.Navigation("Category");

                    b.Navigation("GroupName");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.MemberSubscription", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Forum");

                    b.Navigation("Member");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.OldUserInRole", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.OldRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Poll", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Post", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PollAnswer", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Poll", "Poll")
                        .WithMany("PollAnswers")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PollVote", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Poll", "Poll")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Post", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Forum", "Forum")
                        .WithMany("Posts")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Member", "LastPostAuthor")
                        .WithMany()
                        .HasForeignKey("LastPostAuthorId");

                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Forum");

                    b.Navigation("LastPostAuthor");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.PostReply", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnitzCore.Data.Models.Post", "Topic")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ForumUser", b =>
                {
                    b.HasOne("SnitzCore.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.ArchivedPost", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Category", b =>
                {
                    b.Navigation("Forums");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Forum", b =>
                {
                    b.Navigation("ArchivedPosts");

                    b.Navigation("ForumModerators");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.GroupName", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Member", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Poll", b =>
                {
                    b.Navigation("PollAnswers");

                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("SnitzCore.Data.Models.Post", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
